# Generated by Django 3.1.5 on 2021-06-03 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0002_auto_20210602_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='alumno',
            field=models.ForeignKey(default='000-0', on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno'),
        ),
    ]
