# Generated by Django 3.1.5 on 2021-06-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
